default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: markettincer_db_02h3_user
  password: K3lMReJWk2zLl09Gbl4OIuxbiPREQySc
  host: dpg-cv5ik8rqf0us73f0pisg-a.oregon-postgres.render.com
  port: 5432

development:
  <<: *default
  database: markettincer_db

test:
  <<: *default
  database: markettincer_db_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: postgres
  username: postgres_admin
  password: postgres_admin_password
  host: marketincer-prod.cde64o6y2zb8.us-east-2.rds.amazonaws.com
  # host: marketincer-rds.cxmomsg8m9f6.us-east-2.rds.amazonaws.com
  port: 5432
  # url: postgresql://markettincer_db_2txk_user:fh4n7a2WdLBtfCdbQMQd6lOHqzon7i2v@dpg-cvpul9q4d50c73bv611g-a/markettincer_db_2txk

# Action Cable configuration
cable:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: markettincer_db
  username: markettincer_db_user
  password: oOAnoNuCGbyo9MgbBOthXW5rnoPaviLu
  host: dpg-cufhhvbtq21c73f652tg-a.oregon-postgres.render.com
  port: 5432

queue:
  <<: *default
  database: markettincer_db

cache:
  <<: *default
  database: markettincer_db
