default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: markettincer_db_user
  password: oOAnoNuCGbyo9MgbBOthXW5rnoPaviLu
  host: dpg-cufhhvbtq21c73f652tg-a.oregon-postgres.render.com
  port: 5432

development:
  <<: *default
  database: markettincer_db

test:
  <<: *default
  database: markettincer_db

production:
  <<: *default
  database: markettincer_db
  url: <%= ENV['DATABASE_URL'] %>

# Add this section for Action Cable
cable:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: markettincer_db
  username: markettincer_db_user
  password: oOAnoNuCGbyo9MgbBOthXW5rnoPaviLu
  host: dpg-cufhhvbtq21c73f652tg-a.oregon-postgres.render.com
  port: 5432

queue:
  <<: *default
  database: markettincer_db

cache:
  <<: *default
  database: <%= ENV['DB_NAME'] || 