default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: markettincer_db_02h3_user
  password: K3lMReJWk2zLl09Gbl4OIuxbiPREQySc
  host: dpg-cv5ik8rqf0us73f0pisg-a.oregon-postgres.render.com
  port: 5432

development:
  <<: *default
  database: markettincer_db

test:
  <<: *default
  database: markettincer_db_test

production:
  <<: *default
  database: markettincer_db
  url: postgresql://markettincer_db_02h3_user:K3lMReJWk2zLl09Gbl4OIuxbiPREQySc@dpg-cv5ik8rqf0us73f0pisg-a.oregon-postgres.render.com/markettincer_db

# Action Cable configuration
cable:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: markettincer_db
  username: markettincer_db_user
  password: oOAnoNuCGbyo9MgbBOthXW5rnoPaviLu
  host: dpg-cufhhvbtq21c73f652tg-a.oregon-postgres.render.com
  port: 5432

queue:
  <<: *default
  database: markettincer_db

cache:
  <<: *default
  database: markettincer_db
