default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: markettincer_db_user
  password: oOAnoNuCGbyo9MgbBOthXW5rnoPaviLu
  host: dpg-cufhhvbtq21c73f652tg-a.oregon-postgres.render.com
  port: 5432

development:
  <<: *default
  database: markettincer_db

test:
  <<: *default
  database: markettincer_db

production:
  <<: *default
  database: markettincer_db

cable:
  <<: *default
  database: markettincer_db