# config/sidekiq.yml
:concurrency: 5
:queues:
  - default
  - scheduled_posts

# config/initializers/sidekiq.rb
require 'sidekiq'

Sidekiq.configure_server do |config|
  config.redis = { 
    url: ENV['REDIS_URL'], 
    ssl: true 
  }
end

Sidekiq.configure_client do |config|
  config.redis = { 
    url: ENV['REDIS_URL'], 
    ssl: true 
  }
end