name: Build and Push Docker Image to ECR

on:
  push:
    branches: [main]  # Trigger on pushes to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t marketincer-api .

      - name: Tag Docker image
        run: |
          docker tag marketincer-api:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest

